name = "ocr-checks-worker"
main = "src/index.ts"
compatibility_date = "2024-04-22"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

# Enable Cloudflare logging
[logs]
tail_consumers = [{service = "tail-consumer", environment = "production"}]
timeout = 300

# Enable verbose logging
[build.upload]
format = "service-worker"

# Development environment
[env.dev]
name = "ocr-checks-worker-dev"
route = "dev-api.nolock.social/*"
workers_dev = false
vars = { ENVIRONMENT = "development" }

# Staging environment
[env.staging]
name = "ocr-checks-worker-staging"
route = "staging-api.nolock.social/*"
workers_dev = false
vars = { ENVIRONMENT = "staging" }

# Production environment
[env.production]
name = "ocr-checks-worker"
route = "api.nolock.social/*"
workers_dev = false
vars = { ENVIRONMENT = "production" }

# Environment variables
[vars]
MISTRAL_API_KEY = "vYS1jOH55qvFc5Qqzgn2JHXN3cjMCJQp"