name = "ocr-checks-worker"
main = "src/index.ts"
compatibility_date = "2024-04-22"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

# Logging is enabled by default in Workers
# Debug level is used for development

# Note: CPU limits require a paid plan
# [limits]
# cpu_ms = 50

# Development environment
[env.dev]
name = "ocr-checks-worker-dev"
workers_dev = true
vars = { ENVIRONMENT = "development" }

# Staging environment
[env.staging]
name = "ocr-checks-worker-staging"
route = "staging-api.nolock.social/*"
workers_dev = true
vars = { ENVIRONMENT = "staging" }

# Production environment
[env.production]
name = "ocr-checks-worker"
workers_dev = true
# IMPORTANT: Do not store API keys here, use secrets instead
vars = { ENVIRONMENT = "production" }

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

# Environment variables
# IMPORTANT: DO NOT ADD API KEYS HERE!
# Use Cloudflare Worker secrets instead: wrangler secret put MISTRAL_API_KEY
# Example: echo "your-api-key" | wrangler secret put MISTRAL_API_KEY
[vars]
