name = "ocr-checks-worker"
main = "src/index.ts"
compatibility_date = "2024-04-22"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

# Logging is enabled by default in Workers
# Debug level is used for development

# Note: CPU limits require a paid plan
# [limits]
# cpu_ms = 50

# Development environment
[env.dev]
name = "ocr-checks-worker-dev"
route = "dev-api.nolock.social/*"
workers_dev = false
vars = { ENVIRONMENT = "development" }

# Staging environment
[env.staging]
name = "ocr-checks-worker-staging"
route = "staging-api.nolock.social/*"
workers_dev = false
vars = { ENVIRONMENT = "staging" }

# Production environment
[env.production]
name = "ocr-checks-worker"
workers_dev = true
# IMPORTANT: Replace the API key with your actual Mistral API key
vars = { ENVIRONMENT = "production", MISTRAL_API_KEY = "wHAFWZ8ksDNcRseO9CWprd5EuhezolxE" }

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

# Environment variables
[vars]
# IMPORTANT: This is a placeholder API key. To use this application, replace this with your actual Mistral API key.
# The API key can be obtained from the Mistral AI dashboard at https://console.mistral.ai/
MISTRAL_API_KEY2 = "Yc8LS3Sco5UjbaOHntElp9Lin58eUzLA"